# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build
              cd
              sudo apt-get clean all
              sudo apt-get update
              sudo apt-get install rsync --fix-missing
              rsync -avzh --delete repo ec2-user@www.paratii.video:/home/ec2-user/ -e "ssh -o StrictHostKeyChecking=no"
              ssh -o StrictHostKeyChecking=no ec2-user@www.paratii.video "bash update.sh"
            fi
